Repository esx-framework/esx_core, pull requests merged in 2022-04, with the labels that each got.

#176 fix(esx_sit/config.lua): fixed prop name
  [esx_addons]/esx_sit/config.lua
Labels: awaiting review

#150 Feat: Swedish Tranlsations
  [esx]/es_extended/locales/sv.lua
  [esx]/esx_identity/locales/sv.lua
  [esx]/esx_skin/locales/sv.lua
  [esx]/skinchanger/locales/sv.lua
  [esx_addons]/esx_accessories/locales/sv.lua
  [esx_addons]/esx_ambulancejob/locales/sv.lua
  [esx_addons]/esx_atm/locales/sv.lua
  [esx_addons]/esx_bankerjob/locales/sv.lua
  [esx_addons]/esx_voice/locales/sv.lua
  [esx_addons]/esx_weaponshop/locales/sv.lua
  [esx_addons]/esx_whitelist/locales/sv.lua
  [esx_addons]/instance/locales/sv.lua
Labels: awaiting review, improper title

#167 fix(es_extended/server/main.lua): fix giving weapon components + tints, feat(es_extended/server/main.lua): add distance check
  [esx]/es_extended/config.lua
  [esx]/es_extended/server/main.lua
Labels: awaiting review

#191 refactor(es_extended/server/commands.lua): Alter players command to use `ESX.GetExtendedPlayers()` rather than `ESX.GetPlayers()`
  [esx]/es_extended/server/commands.lua
Labels: awaiting review

#158 fix(esx_legacy): add missing esx_dmvschool sql
  [SQL]/legacy.sql
Labels: awaiting review

#202 Added question_es and ui_es and improved some spanish translation
  [esx_addons]/esx_dmvschool/html/questions_es.js
  [esx_addons]/esx_dmvschool/html/ui_es.html
  [esx_addons]/esx_vehicleshop/locales/es.lua
Labels: improper title

#164 feat(es_extended): Added "Duty" system
  [esx]/es_extended/config.lua
  [esx]/es_extended/locales/en.lua
  [esx]/es_extended/locales/fr.lua
  [esx]/es_extended/server/classes/player.lua
  [esx]/es_extended/server/common.lua
  [esx]/es_extended/server/main.lua
  [esx]/es_extended/server/paycheck.lua
Labels: awaiting review
