Repository esx-framework/esx_core, pull requests merged in 2023-01, with the labels that each got.

#601 refactor(esx_menu_default/client/main.lua): Change isControlePress to ESX.RegisterInput
  [esx]/esx_menu_default/client/main.lua
Labels: awaiting feedback

#794 refactor(esx_society)
  [esx_addons]/esx_society/client/main.lua
  [esx_addons]/esx_society/locales/hu.lua
  [esx_addons]/esx_society/server/main.lua
Labels: wait fix

#834 refactor(esx_service/server/main.lua): Added some new globalstate stuff and fixed stuff
  [esx_addons]/esx_service/server/main.lua
Labels: awaiting review

#838 refactor(esx_banking)
  [esx_addons]/esx_banking/README.md
  [esx_addons]/esx_banking/client/main.lua
  [esx_addons]/esx_banking/config.lua
  [esx_addons]/esx_banking/server/main.lua
  [esx_addons]/esx_property/properties.json
Labels: need test

#847 fix(server.cfg): rename [esx] folder to [core]
  server.cfg
Labels: awaiting review

#855 ESX.OneSync.SpawnVehicle and Command rewrite
  [core]/es_extended/config.lua
  [core]/es_extended/server/commands.lua
  [core]/es_extended/server/onesync.lua
Labels: awaiting review
