Repository esx-framework/esx_core, pull requests merged in 2023-06, with the labels that each got.

#1037 refactor(xPlayer): delete getMeta error message
  [core]/es_extended/server/classes/player.lua
Labels: awaiting feedback

#1056 fix(es_extended/server/classes/player.lua): Fix showNotification function parameters to correspond with esx:showNotification event
  [core]/es_extended/server/classes/player.lua
Labels: awaiting feedback

#1065 ox_inventory - startmoney
  [core]/es_extended/server/main.lua
Labels: reviewed

#1061 feat(multichar): multiple spawns
  [core]/esx_multicharacter/client/main.lua
  [core]/esx_multicharacter/config.lua
Labels: reviewed

#1060 Save Custom Wheels
  [core]/es_extended/client/functions.lua
Labels: awaiting feedback

#1073 Blocking the same character from entering the server
  [core]/esx_multicharacter/server/main.lua
Labels: improper title, awaiting feedback

#1007 add esx:spawnVehicle callback
  [core]/es_extended/server/main.lua
Labels: awaiting feedback

#1042 fix: multicharacter commands + locales formatting
  [core]/es_extended/locales/cs.lua
  [core]/es_extended/locales/da.lua
  [core]/es_extended/locales/de.lua
  [core]/es_extended/locales/en.lua
  [core]/es_extended/locales/es.lua
  [core]/es_extended/locales/fi.lua
  [core]/es_extended/locales/fr.lua
  [core]/es_extended/locales/hu.lua
  [core]/es_extended/locales/it.lua
  [core]/es_extended/locales/nl.lua
  [core]/es_extended/locales/pl.lua
  [core]/es_extended/locales/sl.lua
  [core]/es_extended/locales/sr.lua
  [core]/es_extended/locales/zh-cn.lua
  [core]/esx_identity/locales/cs.lua
  [core]/esx_identity/locales/da.lua
  [core]/esx_identity/locales/en.lua
  [core]/esx_identity/locales/es.lua
  [core]/esx_identity/locales/fi.lua
  [core]/esx_identity/locales/fr.lua
  [core]/esx_identity/locales/it.lua
  [core]/esx_identity/locales/nl.lua
  [core]/esx_identity/locales/pl.lua
  [core]/esx_identity/locales/pt.lua
  [core]/esx_identity/locales/sl.lua
  [core]/esx_identity/locales/sr.lua
  [core]/esx_multicharacter/html/locales/hu.js
  [core]/esx_multicharacter/locales/cs.lua
  [core]/esx_multicharacter/locales/da.lua
  [core]/esx_multicharacter/locales/en.lua
  [core]/esx_multicharacter/locales/es.lua
  [core]/esx_multicharacter/locales/fr.lua
  [core]/esx_multicharacter/locales/hu.lua
  [core]/esx_multicharacter/locales/it.lua
  [core]/esx_multicharacter/locales/nl.lua
  [core]/esx_multicharacter/locales/pt.lua
  [core]/esx_multicharacter/server/commands.lua
  [core]/esx_skin/locales/da.lua
  [core]/esx_skin/locales/en.lua
  [core]/esx_skin/locales/es.lua
  [core]/esx_skin/locales/fi.lua
  [core]/esx_skin/locales/fr.lua
  [core]/esx_skin/locales/it.lua
  [core]/esx_skin/locales/nl.lua
  [core]/esx_skin/locales/pl.lua
  [core]/esx_skin/locales/pt.lua
  [core]/esx_skin/locales/sl.lua
  [core]/esx_skin/locales/sr.lua
  [core]/esx_skin/locales/zh-cn.lua
  [core]/skinchanger/locales/da.lua
  [core]/skinchanger/locales/en.lua
  [core]/skinchanger/locales/es.lua
  [core]/skinchanger/locales/fi.lua
  [core]/skinchanger/locales/fr.lua
  [core]/skinchanger/locales/it.lua
  [core]/skinchanger/locales/nl.lua
  [core]/skinchanger/locales/pl.lua
  [core]/skinchanger/locales/pt.lua
  [core]/skinchanger/locales/sl.lua
  [core]/skinchanger/locales/sr.lua
Labels: awaiting feedback
